In [1]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [2]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
x = torch.tensor([[False, 1,2.0]])
print(x)

tensor([[0., 1., 2.]])


In [4]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.randint(low=0, high=10, size=(3,4))

In [ ]:
torch.rand(3, 4)

In [ ]:
torch.randn((3,4))

In [ ]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))